# Generated by Django 5.1.1 on 2024-09-11 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_goodsentry_delete_moodentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='goodsEntry',
            new_name='Product',
        ),
    ]
